let users = [];

let juegos = [ 
    {imagen: "images/lords of the fallen.jpeg", titulo:"Lords of the Fallen", codigo: 1, precio: 200, genero: "RPG"},
    {imagen: "images/sao game.jpeg", titulo: "Sword Art Online", codigo: 2, precio: 450 },
    {imagen: "images/forza motor.jpeg", titulo: "Forza Motorsport", codigo: 3, precio: 350},
    {imagen: "images/overpass2.jpeg", titulo:"Overpass 2", codigo: 4, precio: 300},
    {imagen: "images/motoGP.jpeg", titulo: "MotoGP24", codigo: 5, precio: 500},
    {imagen: "images/horizon.jpeg" , titulo: "Horizon Zero Dawn", codigo: 6, precio: 450},
    {imagen: "images/hogwarts.jpeg" , titulo: "Hogwarts Legacy", codigo: 7, precio: 600},
    {imagen: "images/biomutant.jpeg" , titulo: "Biomutant", codigo: 8, precio: 750},
    {imagen: "images/all star.jpeg" , titulo: "DreamWorks All Stars", codigo: 9, precio: 400},
    {imagen: "images/dungeons.jpeg", titulo: "Dungeons", codigo: 10, precio: 780},
    {imagen: "images/pes2021.jpeg", titulo: "Football 2021", codigo: 11, precio: 900},
    {imagen: "images/forzah5.jpeg", titulo: "Forza Horizon", codigo: 12, precio: 600},
    {imagen: "images/gta5.jpeg", titulo: "Grand Theft Auto 5", codigo: 13, precio: 600},
    {imagen: "images/mafia.jpeg", titulo: "Mafia", codigo: 14, precio: 650},
    {imagen: "images/avengers.jpeg", titulo: "Marvel Avengers", codigo: 15, precio: 850},
    {imagen: "images/metro.jpeg", titulo: "Metro Exodus", codigo: 16, precio: 500},
    {imagen: "images/naruto.jpeg", titulo: "Naruto", codigo: 17, precio: 500},
    {imagen: "images/spiderman.jpeg", titulo: "Spider Man", codigo: 19, precio: 800},
    {imagen: "images/tlou1.jpeg", titulo: "The last of us", codigo: 21, precio: 450},
    {imagen: "images/sims4.jpeg", titulo: "The Sims 4", codigo: 22, precio: 900},
    {imagen: "images/alaskan road truckers.jpeg", titulo: "Alaskna Road Truckers", codigo: 24, precio: 400},
    {imagen: "images/skylines2.jpeg", titulo: "Cities Skylines II", codigo: 25, precio: 600},
    {imagen: "images/all star.jpeg", titulo: "DreamWorks", codigo: 26, precio: 750},
    {imagen: "images/hotweels unleashed.jpeg", titulo: "Hot Wheels", codigo: 27, precio: 900},
    {imagen: "images/smurfs2.jpeg", titulo: "The Smurfs 2", codigo: 28, precio: 850},
    {imagen: "images/aliens dark descent.jpeg", titulo: "Aliens Dark Descent", codigo: 29, precio: 750},
    {imagen: "images/gylt.jpeg", titulo: "GYLT", codigo: 30, precio: 800},
    {imagen: "images/polbridge3.jpeg", titulo: "Poly Bridge 3", codigo: 31, precio: 750},
    {imagen: "images/ratchetclank.jpeg", titulo: "Ratchet and Clank", codigo: 32, precio: 650},
    {imagen: "images/wanted dead.jpeg", titulo: "Wanted Dead", codigo: 34, precio: 600},
    {imagen: "images/isle of man.jpeg", titulo: "TT: Isle Of Man", codigo: 35, precio: 850},
    {imagen: "images/mc legends.jpeg", titulo: "Minecraf Legends", codigo: 36, precio: 900},
    {imagen: "images/gollum.jpeg", titulo: "Gollum", codigo: 37, precio: 650}];

